#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# branch naming pattern
yarn enforce-branch-name '(hotfix|bugfix|feature)/.+' --ignore '(dev|prod|coming-soon)'

# prettier
yarn prettier_check

# eslint
yarn lint-staged

# e2e testing (run last since it takes the longest)
yarn precommit_cypress

# build (can add this in for THOROUGH check but vercel is better at this so I think we gud :))
# nyarn build